name: LatentInvestigation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core ML stuff 
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - cudnn=8.6.0
  
  # Scientific computing
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - pandas=2.0.3
  
  # Visualization
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  
  # Dev tools
  - jupyter=1.0.0
  - jupyterlab=4.0.3
  - ipywidgets=8.1.0
  - tqdm=4.65.0
  - ipython=8.14.0
  
  # Code quality
  - pytest=7.4.0
  - black=23.7.0
  - flake8=6.1.0
  - mypy=1.4.1
  
  # Package management
  - pip=23.2.1
  
  # Install pip packages
  - pip:
    # Model libraries
    - transformers==4.35.0
    - timm==0.9.7
    - einops==0.7.0
    
    # Experiment tracking
    - wandb==0.15.8
    - tensorboard==2.14.0
    - tensorboardX==2.6.2
    
    # Configuration
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - python-dotenv==1.0.0
    
    # Computer vision
    - opencv-python==4.8.0.76
    - albumentations==1.3.1
    - kornia==0.7.0
    
    # 3D rendering (for ShapeNet)
    - trimesh==4.0.0
    - pyrender==0.1.45
    - pyglet==1.5.27  
    
    - umap-learn==0.5.4
    - scikit-learn-extra==0.3.0
    
    - rich==13.5.2  
    - typer==0.9.0 
    - pyyaml==6.0.1
    - h5py==3.9.0 
    - gdown==4.7.1
