# Linear Probe Configuration
_target_: src.probing.probes.LinearProbe

# Probe architecture
type: linear
input_dim: 768  # this is set based on the model
output_dim: 2   # For viewpoint regression (azimuth, elevation)

# Task configuration
task_type: regression  # or classification is also supported

# Regularization
dropout_rate: 0.0
bias: true

# Training and evaluation are handled via the `training` and `evaluation` config groups
