# Main configuration file
defaults:
  - datasets: shapenet_voxel_meshes
  - _self_

# Global settings
data_dir: ./data
seed: 42

# Experiment settings
experiment:
  name: shapenet_reconstruction_baseline
  version: 1

# Logging
log_level: INFO
