# Main experiment configuration for Phase 1 probing
defaults:
  - models: dinov2 # Switched to dinov2 for voxel reconstruction
  - datasets: shapenet_voxel_meshes # Switched to voxel dataset
  - probing: voxel # Default to voxel probe config
  - _self_

# Experiment metadata
experiment:
  name: phase1_dinov2_voxel_reconstruction
  description: "Probing DINOv2 for 3D voxel reconstruction"
  version: 1

# Hardware settings
device: cuda # or cpu
num_workers: 4

# Batch sizes
extraction_batch_size: 64  
probing_batch_size: 128    

# Probing task configuration
probing:
  task_type: voxel_reconstruction 

  
  # Which probe types to run
  probe_types:
    - voxel
    # - linear # Can add linear/mlp later if we define a flattened voxel prediction task
    # - mlp
  
 
  voxel:
    type: voxel

    training:
      optimizer:
        _target_: torch.optim.Adam
        lr: 0.001
        weight_decay: 1e-4
      
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        mode: max 
        factor: 0.5
        patience: 10
        min_lr: 1e-6
      
      epochs: 30
      early_stopping_patience: 15 
      batch_size: 64

  # Linear probe settings
  linear:
    type: linear
    dropout_rate: 0.0
    bias: true
    
    training:
      optimizer:
        _target_: torch.optim.Adam
        lr: 0.001
        weight_decay: 1e-4
      
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        mode: min
        factor: 0.5
        patience: 10
        min_lr: 1e-6
      
      epochs: 30
      early_stopping_patience: 15
      batch_size: 64
  
  # MLP probe settings
  mlp:
    type: mlp
    hidden_dims: [256, 128]
    activation: relu
    dropout_rate: 0.1
    batch_norm: false
    bias: true
    
    training:
      optimizer:
        _target_: torch.optim.Adam
        lr: 0.001
        weight_decay: 1e-4
      
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        mode: min
        factor: 0.5
        patience: 10
        min_lr: 1e-6
      
      epochs: 40
      early_stopping_patience: 15
      batch_size: 64

# Paths
results_dir: ./results
cache_dir: ./cache

# Logging
log_level: INFO

# Wandb integration 
wandb:
  enabled: false 
  project: latent-investigation
  entity: cse493g1_drn 
  tags:
    - phase1
    - voxel_reconstruction # Updated tag
    - ${models.model_name}

# Reproducibility
seed: 42
