# Main experiment configuration for Phase 1 probing
defaults:
  - models: dinov2  # or ijepa, mocov3, supervised_vit
  - datasets: shapenet_3dr2n2
  - probing: linear_probe
  - _self_

# Experiment metadata
experiment:
  name: phase1_dinov2_viewpoint_probing
  description: "Probing dinov2 for viewpoint prediction"
  version: 1

# Hardware settings
device: cuda  # or cpu
num_workers: 4

# Batch sizes
extraction_batch_size: 128  # For feature extraction
probing_batch_size: 256    # For probe training

# Probing task configuration
probing:
  task_type: viewpoint_regression # regression for viewpoint, classification for shape
  output_dim: 2          # azimuth + elevation for viewpoint
  
  # Which probe types to run
  probe_types:
    - linear
    - mlp
  
  # Linear probe settings
  linear:
    type: linear
    dropout_rate: 0.0
    bias: true
    
    training:
      optimizer:
        _target_: torch.optim.Adam
        lr: 0.001
        weight_decay: 1e-4
      
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        mode: min
        factor: 0.5
        patience: 10
        min_lr: 1e-6
      
      epochs: 30
      early_stopping_patience: 15
      batch_size: 64
  
  # MLP probe settings
  mlp:
    type: mlp
    hidden_dims: [256, 128]
    activation: relu
    dropout_rate: 0.1
    batch_norm: false
    bias: true
    
    training:
      optimizer:
        _target_: torch.optim.Adam
        lr: 0.001
        weight_decay: 1e-4
      
      scheduler:
        _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
        mode: min
        factor: 0.5
        patience: 10
        min_lr: 1e-6
      
      epochs: 30
      early_stopping_patience: 15
      batch_size: 64

# Paths
results_dir: ./results
cache_dir: ./cache

# Logging
log_level: INFO

# Wandb integration 
wandb:
  enabled: true
  project: latent-investigation
  entity: cse493g1_drn 
  tags:
    - phase1
    - viewpoint_probing
    - ${models.model_name}

# Reproducibility
seed: 42
