# ShapeNet 3D-R2N2 Dataset Configuration
_target_: src.datasets.shapenet_voxel_meshes.ShapeNetVoxelMeshes

name: shapenet_voxel_meshes
render_root: ${oc.env:DATA_DIR,../data}/ShapeNetRendering
voxel_root: ${oc.env:DATA_DIR,../data}/ShapeNetVox32
categories: null  

# Dataset preparation options
preparation:
  # render_tar_path: null 
  # voxel_tar_path: null  
  render_url: "http://cvgl.stanford.edu/data2/ShapeNetRendering.tgz"
  voxel_url: "http://cvgl.stanford.edu/data2/ShapeNetVox32.tgz" 
  auto_download: true  

# Transform pipeline for images
transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: 256
    - _target_: torchvision.transforms.CenterCrop
      size: 224
    - _target_: torchvision.transforms.ToTensor

# DataLoader configuration
dataloader:
  batch_size: 32 
  num_workers: 4 
  pin_memory: true
  drop_last: true  
# Dataset splits
splits:
  train: train
  val: val
  test: test

  train_ratio: 0.7
  val_ratio: 0.15
  seed: 42 
  subset_percentage: 0.08